"""Green Certificate Ledger - Renewable Energy Certificate tracking.

Every kWh of solar energy traded generates a fractional REC entry.
The ledger provides:
- Per-agent green energy provenance trail
- Aggregate grid-level renewable statistics
- x402-paywalled audit API endpoint (monetizes certificate data)
"""

from __future__ import annotations

import hashlib
import time
from dataclasses import dataclass, field
from typing import Optional

from agents import AgentType, TradeMatch


@dataclass
class GreenCertificate:
    """A single Renewable Energy Certificate entry."""

    cert_id: str
    source_agent: str
    buyer_agent: str
    seller_type: str  # AgentType.value string for enum-safe renewable check
    kwh: float
    price_usd_per_kwh: float
    tick: int
    sim_hour: float
    timestamp: float = field(default_factory=time.time)
    tx_hash: Optional[str] = None

    @property
    def is_renewable(self) -> bool:
        """Only solar sources generate valid RECs."""
        return self.seller_type == AgentType.SOLAR.value


class CertificateLedger:
    """Tracks all green energy certificates generated by the grid.

    Each solar trade automatically mints a REC entry. Battery-sourced
    energy inherits green status only if the battery was charged from solar
    (tracked via provenance chain).
    """

    def __init__(self):
        self.certificates: list[GreenCertificate] = []
        self._agent_certs: dict[str, list[GreenCertificate]] = {}
        self._total_green_kwh: float = 0.0
        self._total_kwh: float = 0.0
        self._merkle_leaves: list[str] = []

    def record_trade(
        self,
        trade: TradeMatch,
        sim_hour: float,
        seller_type: str,
    ) -> Optional[GreenCertificate]:
        """Record a trade and mint a REC if the source is renewable.

        Args:
            trade: The matched trade from the grid engine.
            sim_hour: Current simulated hour for metadata.
            seller_type: Type of the selling agent ("solar", "battery", "consumer").

        Returns:
            A GreenCertificate if the trade qualifies, else None.
        """
        # BUG FIX: Always increment total_kwh FIRST (was only incrementing when seller was solar)
        self._total_kwh += trade.amount_kwh

        # Only solar-originated energy gets a green certificate
        # BUG FIX: seller_type is already a string (from agent_type.value), so direct comparison works
        is_green = seller_type == "solar"
        if not is_green:
            return None

        cert_input = f"{trade.seller_id}:{trade.buyer_id}:{trade.tick}:{trade.amount_kwh}"
        cert_id = "REC-" + hashlib.sha256(cert_input.encode()).hexdigest()[:12]

        cert = GreenCertificate(
            cert_id=cert_id,
            source_agent=trade.seller_id,
            buyer_agent=trade.buyer_id,
            seller_type=seller_type,
            kwh=trade.amount_kwh,
            price_usd_per_kwh=trade.price_usd_per_kwh,
            tick=trade.tick,
            sim_hour=sim_hour,
            tx_hash=trade.tx_hash,
        )

        self.certificates.append(cert)
        self._total_green_kwh += trade.amount_kwh

        # Index by buyer for per-agent queries
        if trade.buyer_id not in self._agent_certs:
            self._agent_certs[trade.buyer_id] = []
        self._agent_certs[trade.buyer_id].append(cert)

        # Add to Merkle tree leaves for tamper-proof batch verification
        leaf = hashlib.sha256(
            f"{cert_id}:{cert.source_agent}:{cert.buyer_agent}:{cert.kwh}:{cert.timestamp}".encode()
        ).hexdigest()
        self._merkle_leaves.append(leaf)

        return cert

    def get_agent_certificates(self, agent_id: str) -> list[dict]:
        """Get all green certificates for a specific agent."""
        certs = self._agent_certs.get(agent_id, [])
        return [
            {
                "cert_id": c.cert_id,
                "source": c.source_agent,
                "kwh": c.kwh,
                "price_usd_per_kwh": c.price_usd_per_kwh,
                "tick": c.tick,
                "sim_hour": c.sim_hour,
                "timestamp": c.timestamp,
                "tx_hash": c.tx_hash,
            }
            for c in certs
        ]

    def get_merkle_root(self) -> str:
        """Compute Merkle root of all certificate leaves.

        In production, this root would be posted to Arc as a single
        on-chain transaction for tamper-proof batch verification.
        """
        if not self._merkle_leaves:
            return "0x" + "0" * 64

        leaves = list(self._merkle_leaves)
        while len(leaves) > 1:
            if len(leaves) % 2 == 1:
                leaves.append(leaves[-1])
            next_level = []
            for i in range(0, len(leaves), 2):
                combined = leaves[i] + leaves[i + 1]
                next_level.append(hashlib.sha256(combined.encode()).hexdigest())
            leaves = next_level

        return "0x" + leaves[0]

    @property
    def stats(self) -> dict:
        """Aggregate statistics for the dashboard."""
        green_pct = (
            (self._total_green_kwh / self._total_kwh * 100.0)
            if self._total_kwh > 0
            else 0.0
        )
        return {
            "total_certificates": len(self.certificates),
            "total_green_kwh": round(self._total_green_kwh, 6),
            "total_kwh_traded": round(self._total_kwh, 6),
            "green_percentage": round(green_pct, 2),
            "merkle_root": self.get_merkle_root(),
            "unique_buyers": len(self._agent_certs),
        }
